name: common
description: Common classes shared among the public and private codebase of mobileraker
version: 2.6.7
homepage: mobileraker.com

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.7.2'

#dependency_overrides:
#  intl: ^0.18.1 # required due to awesome notifications and formbuilder


dependencies:
  flutter:
    sdk: flutter

  #network
  web_socket_channel: ^2.1.0
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  flutter_web_auth: ^0.5.0
  http: ^1.0.0

  #firebase
  firebase_core_platform_interface: ^4.8.0
  firebase_core: ^2.16.0
  firebase_analytics: ^10.5.0
  firebase_app_check: ^0.2.0
  firebase_crashlytics: ^3.3.6
  firebase_remote_config: ^4.2.6
  cloud_firestore: ^4.9.2

  #purchases
  purchases_flutter: ^5.3.0

  #notification
  awesome_notifications_core: ^0.8.1
  awesome_notifications: ^0.8.2
  awesome_notifications_fcm: ^0.8.0
  live_activities: ^1.9.0


  #routing
  go_router: ^6.2.0

  #architecture
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.3.8
  riverpod_annotation: ^2.1.6
  json_annotation: ^4.8.1
  worker_manager: ^6.3.1

  #i18n
  easy_localization: ^3.0.3

  #persisstent
  path_provider: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.1

  #ui
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons.git
  flutter_svg: ^2.0.5
  progress_indicators: ^1.0.0

  #misc
  logger: ^1.3.0
  rxdart: ^0.27.3
  stringr: ^1.0.0
  collection: ^1.17.0
  uuid: ^3.0.5
  network_info_plus: ^4.0.2
  permission_handler: ^11.0.0
  url_launcher: ^6.1.6
  package_info_plus: ^4.1.0

  #crypto
  hashlib_codecs: ^2.2.0
  hashlib: ^1.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^2.0.3
  riverpod_lint: ^2.1.0
  custom_lint: ^0.5.3
  build_runner: ^2.3.3
  freezed: ^2.4.1
  json_serializable: ^6.4.1
  riverpod_generator: 2.3.2 #// Todo use ^ again once dependency error is fixed
  hive_generator: ^2.0.0

flutter:
