name: common
description: Common classes shared among the public and private codebase of mobileraker
version: 0.0.1
homepage: mobileraker.com

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.2'

dependencies:
  flutter:
    sdk: flutter

  #network
  web_socket_channel: ^2.1.0
  http: ^0.13.4
  flutter_web_auth: ^0.5.0

  #firebase
  firebase_core_platform_interface: ^4.8.0
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_app_check: ^0.1.5+1
  firebase_crashlytics: ^3.3.4
  firebase_remote_config: ^4.2.4
  cloud_firestore: ^4.8.0

  #purchases
  purchases_flutter: ^5.3.0

  #notification
  awesome_notifications: ^0.7.5-dev.3
  awesome_notifications_fcm: ^0.7.5-dev.3

  #architecture
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.8
  riverpod_annotation: ^2.1.2
  json_annotation: ^4.8.1

  #i18n
  easy_localization: ^3.0.0

  #persisstent
  path_provider: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #misc
  logger: ^1.3.0
  rxdart: ^0.27.3
  stringr: ^1.0.0
  collection: ^1.17.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.0.1
  custom_lint: ^0.5.2
  build_runner: ^2.3.3
  freezed: ^2.2.1
  json_serializable: ^6.4.1
  riverpod_generator: ^2.2.6
  hive_generator: ^2.0.0

flutter:
