name: Build Android
on:
  workflow_dispatch:
  push:
    tags:
      - 'android*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.3.10'
      - run: echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 -d > ./android/app/google-services.json
      - run: echo ${{ secrets.KEY_PROPERTIES }} | base64 -d > ./android/key.properties
      - run: echo ${{ secrets.PLAY_STORE_JKS }} | base64 -d > ./android/app/gps.jks
      - run: echo ${{ secrets.AWESOME_NOTI_LICENSE }} | base64 -d > ./lib/license.dart
      - run: echo ${{ secrets.FIREBASE_OPTIONS }} | base64 -d > ./lib/firebase_options.dart
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - run: flutter build apk --release
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.changelog.outputs.changelog }}

          
